BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
LTO_ENABLE = yes

MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
COMMAND_ENABLE = no
LEADER_ENABLE = no
CONSOLE_ENABLE = no
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
OLED_ENABLE = no
